export const csvTemplates = {
  'top_level_active.csv': ['currentId'],
  'top_level_elections.csv': ['id', 'type', 'name', 'status', 'year', 'isDataReady'],
  'election_meta.csv': ['id', 'type', 'name', 'status', 'year', 'shortName', 'description'],
  'election_visuals.csv': ['id', 'role', 'title', 'description', 'alt', 'imageUrl'],
  'parties.csv': ['id', 'name', 'shortName', 'color'],
  'prefectures.csv': ['id', 'name', 'region', 'districtCount'],
  'proportional_blocks.csv': ['id', 'name', 'seats'],
  'districts.csv': ['id', 'name', 'prefectureId', 'winnerMemberId'],
  'candidates.csv': [
    'id',
    'name',
    'partyId',
    'prefectureId',
    'districtId',
    'proportionalBlockId',
    'photoUrl',
    'profileUrl',
    'wins',
    'status',
  ],
  'members.csv': ['id', 'name', 'partyId', 'prefectureId', 'districtId', 'proportionalBlockId', 'photoUrl', 'wins', 'status'],
  'single_member_district_results.csv': [
    'id',
    'electionId',
    'prefectureId',
    'prefecture',
    'districtName',
    'districtNumber',
    'candidateId',
    'candidateName',
    'partyId',
    'partyName',
    'status',
    'votes',
    'voteRate',
    'turnout',
    'photoUrl',
    'profileUrl',
    'mapX',
    'mapY',
    'mapZ',
  ],
  'proportional_results.csv': [
    'id',
    'electionId',
    'blockId',
    'blockName',
    'partyId',
    'partyName',
    'status',
    'seats',
    'voteRate',
    'turnout',
    'mapX',
    'mapY',
    'mapZ',
  ],
  'summary.csv': ['totalSeats', 'districtSeats', 'proportionalSeats', 'reportingRate', 'updatedAt'],
  'summary_party_seats.csv': ['partyId', 'seats'],
};
